language: csharp
solution: ./src/FluentValidation.Validators.UnitTestExtension.sln
script:
  - xbuild /p:Configuration=Release ./src/FluentValidation.Validators.UnitTestExtension.sln
  - mono ./src/packages/xunit.runner.console.*/tools/xunit.console.exe ./src/FluentValidation.Validators.UnitTestExtension.Tests/bin/Release/FluentValidation.Validators.UnitTestExtension.Tests.dll